config/routes.rb
Mortgage::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations'}

  get 'sessions/new'

  get 'registrations/new'
  get 'registrations/edit'

  get 'authentications/index'
  get 'authentications/create'
  get 'authentications/destroy'

  get 'schedule/ideal'
  get 'schedule/actual'

  #get 'payments/new'
  #get 'payments/edit'
  #get 'payments/destroy'
  #get 'payments/ideal'
  get 'payments/actual'
  get 'payments/session_create'
  #match 'payments/session_create', :via => :put
  get 'session_payments/actual'

  get 'loans/summary'
  get 'loans/save_session'

  match '/auth/failure' => 'authentications#failure'
  match '/auth/:provider/callback' => 'authentications#create'

  resources :pages, :only => :show
  resources :session_payments #, :path => "/session/payments"
  resources :loans, :except => :edit do
    resources :payments, :except => :index, :shallow => true
  end

  root :to => 'loans#index'

end

app/models/loan.rb
include ActionView::Helpers::TextHelper

class Loan < ActiveRecord::Base

  validates_presence_of :asset_price, :down_payment, :escrow_payment, :first_payment, :interest_rate,
                        :payments_per_year, :planned_payment, :years, :name
  validates_numericality_of :asset_price, :down_payment, :escrow_payment, :interest_rate, :payments_per_year,
                            :planned_payment, :years

  attr_accessible :asset_price, :down_payment, :escrow_payment, :first_payment, :interest_rate, :payments_per_year,
                  :planned_payment, :years, :name, :payments

  belongs_to :user
  #has_one :schedule
  has_many :payments, :dependent => :destroy, :order => 'date'

  # need this?
  accepts_nested_attributes_for :payments

  def loan_amount
     asset_price - down_payment if asset_price and down_payment
  end

  def expected_payments
    years * payments_per_year if years and payments_per_year
  end

  def rate
    interest_rate / ( 100.0 * payments_per_year) if interest_rate and payments_per_year
  end

  def loan_payment
    if rate and loan_amount and expected_payments
      rate * loan_amount / ( 1 -  ( 1 + rate ) ** ( -1 * expected_payments ) )
    end
  end

  def last_payment
    last_loan_payment + escrow_payment if last_loan_payment
  end

  def last_loan_payment
    if rate and loan_amount and real_payment and actual_payments
      actual_last_payment = loan_amount * ( 1 + rate ) ** actual_payments - ( real_payment / rate ) * ( ( 1 + rate ) ** actual_payments - 1 )
      actual_last_payment + real_payment
    end
  end

  def real_payment
    planned_payment - escrow_payment if planned_payment and escrow_payment
  end

  def actual_payments
    if rate and loan_amount and real_payment
      begin
        number_of_payments = (-1 * Math.log( 1 - rate * loan_amount / real_payment) / Math.log( 1 + rate) ).ceil
        (number_of_payments > 0) ? number_of_payments : 0
      rescue
        0
      end
    end
  end

  def payoff_time
    if actual_payments and payments_per_year
      years = actual_payments / payments_per_year
      months = actual_payments % payments_per_year * 12 / payments_per_year
      "#{ pluralize(years, "year") } and #{ pluralize(months, "month") }"
    end
  end

  def payoff_date
    first_payment + (actual_payments * 12 / payments_per_year - 1).months if first_payment and actual_payments
  end

  def actual_payment
    loan_payment + escrow_payment if loan_payment and escrow_payment
  end

  def total_interest
    if planned_payment and actual_payments and last_payment and loan_amount
      interest = planned_payment * ( actual_payments - 1 ) + last_payment - loan_amount
      (interest > 0) ? interest : 0
    end
  end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :new, :create, :summary, :ideal_schedule, :actual_payments,
                                                 :save_session, :current_schedule]

  def save_session
    #params[:loan][:payments] = session[:loan][:payments] if session[:loan]
    #payments = session[:loan][:payments] if session[:loan]
    #session[:payments] = params[:payments]
    session[:loan] = params[:loan]
    session[:payments] ||= []
    #session[:loan][:payments] = payments if payments
    render :nothing => true
  end

  def summary
    @loan = Loan.new(params[:loan])
    render :partial => "summary"
  end

  def index
    if user_signed_in?
      @loans = current_user.loans
    else
      redirect_to new_loan_path
    end
  end

  def new
    #reset_session
    if session[:loan]
      @loan = Loan.new(session[:loan])
      #@loan = Loan.new(params[:loan])
    else
      @loan = Loan.new
      @loan.payments_per_year = 12
      @loan.interest_rate = "5.000"
      @loan.escrow_payment = "0.00"
      @loan.first_payment = Time.now.to_date
    end
    render "calculator"
  end

  def show
    @loan = current_user.loans.find(params[:id])
    if @loan.payments.last
      @payment = @loan.payments.last.dup
      @payment.date = @payment.date + (12 / @loan.payments_per_year).months
    else
      @payment = @loan.payments.new
      @payment.date = @loan.first_payment
    end
    @payments = @loan.payments
    render "calculator"
  end

  def create
    if user_signed_in?
      @loan = current_user.loans.new(params[:loan])
      @payments = []

      #if @loan.save
        if session[:payments]
          #Rails.logger.debug session[:payments].to_yaml

          #@loan.payments = session[:payments]
          #@payments.save

          #@payments = session[:payments].collect { |payment| @loan.payments.new(:payments => payment).save }

          #@payments = session[:payments].collect { |payment| @loan.payments.new(payment) }
          #if @payments.all?(&:valid?)
          #  @payments.each(&:save!)
          #end

          #@payments = session[:payments].collect { |payment|
          #  new_payment = Payment.new(payment)
          #  new_payment.loan_id = @loan.id
          #  new_payment.save
          #}

        session[:payments].each { |payment|
            #new_payment = @loan.payments.new()
            #Rails.logger.debug new_payment.to_yaml
            #new_payment.attributes = payment
            Rails.logger.debug payment.to_yaml
            #Rails.logger.debug new_payment.to_yaml
            #@payments << new_payment

            #@payments << @loan.payments.new(payment)

            #Rails.logger.debug @payments.to_yaml

            @loan.payments.new(payment)
          }

        end

        if @loan.valid? && @payments.all?(&:valid?)
          @loan.save!
          @payments.each(&:save!)
          flash[:notice] = 'Loan was successfully created.'
          session[:loan] = nil
          session[:payments] = nil
        else
          session[:loan] = params[:loan]
        end

      #else
      #  session[:loan] = params[:loan]
      #end
      render "calculator"
    else
      session[:loan] = params[:loan]
      redirect_to user_session_path, notice: 'You must be signed in to save.'
    end
  end

  def update
    @loan = current_user.loans.find(params[:id])
    if @loan.update_attributes(params[:loan])
      @payment = @loan.payments.last.dup
      @payment.date = @payment.date + (12 / @loan.payments_per_year).months
      flash[:notice] = 'Loan was successfully updated.'
    end
    render "calculator"
  end

  def destroy
    @loan = current_user.loans.find(params[:id])
    @loan.destroy
    redirect_to loans_url
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_fundamentals.html.erb
<%= form_for(@loan) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="span-24">
      <%= f.hidden_field :id %>
      <div class="field span-8 append-1">
        <%= f.label :name %><br/>
        <%= f.text_field :name, :class => "text" %>
      </div>
      <div class="actions span-14 append-1 last">
        <% if user_signed_in? %>
            <button type="button" class="back-button" formaction="/loans">My Loans</button>
            <button type="submit" class="save-button alert-save">Save</button>
        <% else %>
            <button class="save-button">Save</button>
        <% end %>
      </div>
    </div>
    <div class="span-7 prepend-1">
      <div class="field">
        <%= f.label :asset_price %><br/>
        <%= f.text_field :asset_price, :class => "text span-7 focus", :value => number_with_precision(f.object.asset_price, :precision => 2) %>
      </div>
      <div class="field">
        <%= f.label :down_payment %><br/>
        <%= f.text_field :down_payment, :class => "text span-7", :value => number_with_precision(f.object.down_payment, :precision => 2) %>
      </div>
    </div>
    <div class="span-7 prepend-1">
      <div class="field">
        <%= f.label :interest_rate %><br/>
        <%= f.text_field :interest_rate, :class => "text span-7", :value => number_with_precision(f.object.interest_rate, :precision => 3) %>
      </div>
      <div class="field">
        <%= f.label :escrow_payment %><br/>
        <%= f.text_field :escrow_payment, :class => "text span-7", :value => number_with_precision(f.object.escrow_payment, :precision => 2) %>
      </div>
      <div class="field">
        <%= f.label :planned_payment %><br/>
        <%= f.text_field :planned_payment, :class => "text span-7", :value => number_with_precision(f.object.planned_payment, :precision => 2) %>
      </div>
    </div>
    <div class="span-7 prepend-1 last">
      <div class="field">
        <%= f.label :years %><br/>
        <%= f.text_field :years, :class => "text span-7" %>
      </div>
      <div class="field">
        <%= f.label :payments_per_year %><br/>
        <%= f.text_field :payments_per_year, :class => "text span-7" %>
      </div>
      <div class="field">
        <%= f.label :first_payment %><br/>
        <%= f.text_field :first_payment, :class => "text span-5 date-picker" %>
      </div>
    </div>
<% end %>

app/views/loans/_ideal_schedule.html.erb
<% if @schedule %>
    <table>
      <thead>
      <tr>
        <th></th>
        <th>Date</th>
        <th>Total</th>
        <th>To Principle</th>
        <th>Interest</th>
        <th>Escrow</th>
        <th>Payment</th>
      </tr>
      </thead>

      <tbody>
      <% @schedule.each do |line| %>
          <tr class="<%= line[:class] %>">
            <td><%= line[:number] %></td>
            <td><%= line[:date] %></td>
            <td><b><%= number_to_currency line[:total] %></b></td>
            <td><%= number_to_currency line[:to_principle] %></td>
            <td><%= number_to_currency line[:interest] %></td>
            <td><%= number_to_currency line[:escrow] %></td>
            <td><b><%= number_to_currency line[:payment] %></b></td>
          </tr>
      <% end %>
      </tbody>

    </table>
<% else %>
    <h2>Schedule is not loaded, perhaps you need to enter more data</h2>
<% end %>

app/views/loans/_summary.html.erb
<%= form_for(@loan, :html => {:id => "new_loan_summary_form"}) do |f| %>
    <div class="span-9 prepend-1">
      <fieldset>
        <legend>Payments</legend>
        <div class="field">
          <%= f.label :actual_payment, "Required Payment (w/o escrow: #{number_to_currency(@loan.loan_payment)})" %><br/>
          <%= f.text_field :actual_payment, :class => "title", :value => number_with_precision(f.object.actual_payment, :precision => 2) %>
        </div>
        <div class="field">
          <%= f.label :last_payment, "Last payment instead of #{number_to_currency(@loan.planned_payment)}<br /> (w/o escrow #{number_to_currency(@loan.last_loan_payment)})".html_safe %><br/>
          <%= f.text_field :last_payment, :class => "title", :value => number_with_precision(f.object.last_payment, :precision => 2) %>
        </div>
        <hr class="space"/>
        <div class="field">
          <%= f.label :expected_payments, "Number of expected payments" %><br/>
          <%= f.text_field :expected_payments, :class => "title" %>
        </div>
        <div class="field">
          <%= f.label :actual_payments %><br/>
          <%= f.text_field :actual_payments, :value => number_with_precision(f.object.actual_payments, :precision => 0), :class => "title" %>
        </div>
      </fieldset>
    </div>
    <div class="span-8 prepend-1">
      <fieldset class="span-8">
        <legend>Timeframe</legend>
        <div class="field">
          <%= f.label :payoff_date %><br/>
          <%# f.date_select :payoff_date, {}, :class => "title" %>
          <%= f.text_field :payoff_date, :class => "title" %>
        </div>
        <div class="field">
          <%= f.label :payoff_time %><br/>
          <%= f.text_field :payoff_time, :class => "title" %>
        </div>
      </fieldset>
      <fieldset class="span-8">
        <legend>Totals</legend>
        <div class="field">
          <%= f.label :loan_amount %><br/>
          <%= f.text_field :loan_amount, :class => "title", :value => number_with_precision(f.object.loan_amount, :precision => 2) %>
        </div>
        <div class="field">
          <%= f.label :total_interest %><br/>
          <%= f.text_field :total_interest, :class => "title", :value => number_with_precision(f.object.total_interest, :precision => 2) %>
        </div>
      </fieldset>
    </div>
<% end %>

app/views/loans/calculator.html.erb
<div id="loan_fundamentals" class="span-24">
  <%= render 'fundamentals' %>
</div>

<hr class="space"/>

<div id="calculated" class="span-23 prepend-1">
  <div id="tabs" class="span-22">
    <ul id="tabs-list">
      <li><a href="#summary_tab">Summary</a></li>
      <li><a href="#actual_payments_tab">Actual Payments</a></li>
      <li><a href="#current_schedule_tab">Actual Schedule</a></li>
      <!--<li><a href="#planned_payments_tab">Ideal Payments</a></li>-->
      <li><a href="#ideal_schedule_tab">Ideal Schedule</a></li>
    </ul>
    <div id="spinner" class="prepend-1">
      <hr class="space" />
      <h3><img src="/assets/ui-anim_basic_16x16.gif">Loading...</h3>
    </div>
    <div id="summary_tab">
      <%# render 'summary' %>
    </div>
    <div id="actual_payments_tab">
      <%# render 'actual_payments' %>
    </div>
    <div id="current_schedule_tab">
      <%# render 'current_schedule' %>
    </div>
    <!--<div id="planned_payments_tab">-->
      <%# render 'planned_payments' %>
    <!--</div>-->
    <div id="ideal_schedule_tab">
      <%# render 'ideal_schedule' %>
    </div>
  </div>
  <div id="payment-form-container">
    <%# if @loan.id %>
    <%# render 'payments/form' %>
    <%# end %>
  </div>
</div>

app/views/loans/index.html.erb
<% title "My Loans"  %>

<table>
<thead>
  <tr>
    <th>Loan</th>
    <th>Asset Price</th>
    <th>Planned Payment</th>
    <th>Actual Payment</th>
    <th>Time Left</th>
    <th></th>
  </tr>
</thead>

<tbody>
<%- if session[:loan] %>
    <tr>
      <td colspan="6"><h4 class="alt"> You have an unsaved loan, click <%= link_to "here", new_loan_path %> to edit it</h4></td>
    </tr>
<% end -%>
<% @loans.each do |loan| %>
  <tr>
    <td><%= link_to loan.name, loan_path(loan), :class => "edit-button" %></td>
    <td><h3><%= number_to_currency(loan.asset_price) %></h3></td>
    <td><h3><%= number_to_currency(loan.planned_payment) %></h3></td>
    <td><h3><%= number_to_currency(loan.actual_payment) %></h3></td>
    <td><h3 class="alt"><%= distance_of_time_in_words(Time.now, loan.payoff_date.to_time) %></h3></td>
    <td><%= link_to 'Delete', loan, method: :delete, data: { confirm: 'Are you sure?' }, :class => "delete-button" %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<button type="button" class="new-button" title="Create" formaction="<%= new_loan_path %>">New Loan</button>