config/routes.rb
Mortgage::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations'}

  get 'sessions/new'

  get 'registrations/new'
  get 'registrations/edit'

  get 'authentications/index'
  get 'authentications/create'
  get 'authentications/destroy'

  get 'schedule/ideal'
  get 'schedule/actual'

  #get 'payments/new'
  #get 'payments/edit'
  #get 'payments/destroy'
  #get 'payments/ideal'
  get 'payments/actual'
  get 'payments/session_create'
  #match 'payments/session_create', :via => :put
  get 'session_payments/actual'

  get 'loans/summary'
  get 'loans/save_session'

  match '/auth/failure' => 'authentications#failure'
  match '/auth/:provider/callback' => 'authentications#create'

  resources :pages, :only => :show
  resources :session_payments #, :path => "/session/payments"
  resources :loans, :except => :edit do
    resources :payments, :except => :index, :shallow => true
  end

  root :to => 'loans#index'

end

app/views/layouts/application.html.erb
<% default_title 'Mortgage Calculator' %>
<%= render :template => 'layouts/defaults' %>
<%= render :template => 'layouts/default_layout' %>

app/views/layouts/default_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= yield :head %>
</head>
<body>
<div class="container">
  <header>
      <%= yield :header %>
  </header>
  <content>
    <div class="span-24 last">
      <%= yield %>
    </div>
  </content>
  <footer>
    <%= yield :footer %>
  </footer>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/defaults.html.erb
<% content_for :head do %>
    <%= favicon_link_tag('/assets/favicon.ico') %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
<% end %>

<% content_for :header do %>
    <nav class="span-24 append-bottom">
      <ul>
        <%= link_to '<li class="left hover">Home</li>'.html_safe, new_loan_path %>
        <%= render :partial => "pages/links", :collection => @display_pages.topbar, :as => :page, :locals => {:classes => "left hover"} %>
        <% if user_signed_in? %>
            <%= link_to '<li class="left hover">My Loans</li>'.html_safe, loans_path %>
            <%= link_to '<li class="left hover">Account</li>'.html_safe, edit_user_registration_path %>
            <%= link_to '<li class="right hover">Sign out</li>'.html_safe, destroy_user_session_path, :method => :delete %>
            <li class="right last lighter"><%= current_user.email %></li>
        <% else %>
            <%= link_to '<li class="right hover">Sign in</li>'.html_safe, user_session_path %>
            <%= link_to '<li class="right hover">Sign up</li>'.html_safe, new_user_registration_path %>
        <% end %>
      </ul>
    </nav>
    <banner>
      <%= link_to logo, root_path, {:class => "right prepend-1"} %>
      <h1 class="left alt append-1"><%= yield(:title) %></h1>
      <% flash.each do |key, value| %>
          <div id="notice" class="left flash <%= key %>"><%= value %></div>
      <% end %>
    </banner>
    <hr/>
<% end %>

<% content_for :sidebar do %>
    <%= render 'shared/sidebar', :sidebar => @display_pages.sidebar %>
<% end %>

<% content_for :userbar do %>
    <% if user_signed_in? %>
        <%= render 'shared/sidebar', :sidebar => @display_pages.userbar %>
    <% end %>
<% end %>

<% content_for :footer do %>
    <nav class="span-24 prepend-top last">
      <ul>
        <%= render :partial => "pages/links", :collection => @display_pages.bottombar, :as => :page, :locals => {:classes => "left hover"} %>
      </ul>
    </nav>
<% end %>

app/views/layouts/pages.html.erb
<% @view_flow.set(:sidebar, '') %>
<%= render :template => 'layouts/defaults' %>
<%= render :template => 'layouts/default_layout' %>